iso_checksum = "https://cdimage.debian.org/cdimage/release/current/arm64/iso-dvd/SHA256SUMS"
iso_name = "debian-13.1.0-arm64-DVD-1.iso"
iso_url = "https://cdimage.debian.org/cdimage/release/current/arm64/iso-dvd/debian-13.1.0-arm64-DVD-1.iso"
vmware_guest_os_type = "arm-debian13-64"
virtualbox_guest_os_type = "Debian13_arm64"
