vm_name = "debian12-arm64"
iso_checksum = "http://cdimage.debian.org/cdimage/release/current/arm64/iso-dvd/SHA256SUMS"
iso_name = "debian-12.0.0-arm64-DVD-1.iso"
iso_url = "https://cdimage.debian.org/cdimage/release/current/arm64/iso-dvd/debian-12.0.0-arm64-DVD-1.iso"
virtualbox_guest_os_type = "Debian_64"
version = "1.0.0"
version_description = "- Debian 12.0.0"
box_description = "Debian 12 (Bookworm) Arm 64bit"
