# -*- mode: ruby -*-
# vi: set ft=ruby :

NAME = 'debian-test-vagrant'



Vagrant.configure(2) do |config|

	arch=`arch`.chomp

	(10..12).each do |version|
		basename = "debian#{version}"
		config.vm.define basename do |machine|
			machine.vm.box = "koalephant/#{basename}-#{arch}-test"
			vmname = "Debian #{version} Test VM (#{arch})"
			[:vmware_workstation, :vmware_fusion, :vmware_desktop].each do |provider|
				machine.vm.provider(provider) do |vm|
					vm.vmx[:displayname] = vmname
				end
			end

			[:parallels, :virtualbox].each do |provider|
				machine.vm.provider provider do |vm|
					vm.name = vmname
				end
			end

		end
	end
end
