# -*- mode: ruby -*-
# vi: set ft=ruby :

NAME = 'debian-test-vagrant'

def archname()
	arch = `uname -m`.chomp
	case arch
	when 'x86_64'
		return 'amd64'
	when 'i686'
		return 'i386'
	when 'aarch64_be', 'aarch64', 'armv8b', 'armv8l'
		return 'arm64'
	else
		return arch
	end
end

Vagrant.configure(2) do |config|

	config.vagrant.plugins = ['vagrant-parallels', 'vagrant-vmware-desktop']

	arch=archname

	(10..12).each do |version|
		basename = "debian#{version}"
		config.vm.define basename do |machine|
			machine.vm.box = "koalephant/#{basename}-#{arch}-test"
			vmname = "Debian #{version} Test VM (#{arch})"
			[:vmware_workstation, :vmware_fusion, :vmware_desktop].each do |provider|
				machine.vm.provider(provider) do |vm|
					vm.vmx[:displayname] = vmname
				end
			end
			machine.vm.provider :parallels do |vm|
				vm.name = vmname
			end

			machine.vm.provider :virtualbox do |vm|
				vm.name = vmname
				vm.customize ['storageattach', :id, '--storagectl', 'IDE Controller', '--port', '0', '--device', '1', '--type', 'dvddrive']

			end
		end
	end
end
